/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParticuliersRouteImport } from './routes/particuliers'
import { Route as ProfessionnelsRouteImport } from './routes/professionnels'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticuliersRoute = ParticuliersRouteImport.update({
  id: '/particuliers',
  path: '/particuliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionnelsRoute = ProfessionnelsRouteImport.update({
  id: '/professionnels',
  path: '/professionnels',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/particuliers': typeof ParticuliersRoute
  '/professionnels': typeof ProfessionnelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/particuliers': typeof ParticuliersRoute
  '/professionnels': typeof ProfessionnelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/particuliers': typeof ParticuliersRoute
  '/professionnels': typeof ProfessionnelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/particuliers' | '/professionnels'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/particuliers' | '/professionnels'
  id: '__root__' | '/' | '/particuliers' | '/professionnels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParticuliersRoute: typeof ParticuliersRoute
  ProfessionnelsRoute: typeof ProfessionnelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/particuliers': {
      id: '/particuliers'
      path: '/particuliers'
      fullPath: '/particuliers'
      preLoaderRoute: typeof ParticuliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionnels': {
      id: '/professionnels'
      path: '/professionnels'
      fullPath: '/professionnels'
      preLoaderRoute: typeof ProfessionnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParticuliersRoute: ParticuliersRoute,
  ProfessionnelsRoute: ProfessionnelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
